disabled = false
locale = "en-us"
languageName = "English"
weight = 1
title = "Plakar | The Open Standard for Backup and Restore"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/general/featured.png"
  description = "Enterprise ready backups with developer friendly tooling. Encrypted, deduplicated snapshots, instant browsing and restore, and zero knowledge workflows across clouds and on-prem."
  locale = "en_US"
  keywords = ["backup", "open-source", "deduplication", "encryption", "plakar", "cloud backup", "database backup"]

[params.author]
  name = "PlakarKorp"
