[[main]]
identifier = "product"
name = "Product"
url = "#"
weight = 10
[[main.params]]
  enabled = true

[[main]]
identifier = "resources"
name = "Resources"
url = "#"
weight = 20
[[main.params]]
  enabled = true

[[main]]
identifier = "integrations"
name = "Integrations"
url = "/integrations/"
weight = 30
[[main.params]]
  enabled = true

[[main]]
identifier = "download"
name = "Download"
url = "/download/"
weight = 40
[[main.params]]
  enabled = true
