colorScheme = "plakar"
defaultAppearance = "light"
autoSwitchAppearance = false
enableSearch = false
enableCodeCopy = false
replyByEmail = false
disableImageOptimization = false
disableTextInHeader = true
giteaDefaultServer = "https://git.fsfe.org"
forgejoDefaultServer = "https://v8.next.forgejo.org"
highlightCurrentMenuArea = false
debugPagesInMeta = false
baseURL = "https://plakar.io/"
#defaultBackgroundImage = "img/background.svg"

[header]
layout = "fixed"
showGithubBadge = true
showDiscordBadge = true
showBlueskyBadge = true

[footer]
showMenu = true
showCopyright = true
showThemeAttribution = false
showAppearanceSwitcher = false
showScrollToTop = true
showDiscordBadge = true
showBlueskyBadge = true
showGithubBadge = true
showLinkedinBadge = true

[homepage]
layout = "custom"
showRecent = false
showRecentItems = 5
showMoreLink = true
showMoreLinkDest = "/community-news/"
cardView = true
cardViewScreenWidth = false
layoutBackgroundBlur = true


[article]
showDate = true
showViews = false
showLikes = false
showDateOnlyInArticle = false
showDateUpdated = false
showAuthor = true
showHero = true
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = false
showDraftLabel = true
showEdit = false
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = true
showTableOfContents = true
showTaxonomies = false
showAuthorsBadges = false
showWordCount = true
showZenMode = true

[list]
showHero = true
heroStyle = "background"
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = false
showBreadcrumbs = false
showSummary = true
showViews = false
showLikes = false
showTableOfContents = false
showCards = false
orderByWeight = false
groupByYear = false
cardView = false
cardViewScreenWidth = false
constrainItemsWidth = false

[sitemap]
excludedKinds = [ "taxonomy", "term" ]

[taxonomy]
showTermCount = true
showHero = false
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = false
cardView = false

[term]
showHero = false
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = true
groupByYear = false
cardView = false
cardViewScreenWidth = false

[firebase]

[fathomAnalytics]

[umamiAnalytics]

[selineAnalytics]

[buymeacoffee]

[verification]

[rssnext]

[axeptio]
clientId = "670b04f487d8b40de2e7f22c"
cookiesVersion = "plakar-fr-EU-2"
enabled = true

[github]
organization = "PlakarKorp"
repository = "plakar"

[discord]
inviteCode = "uuegtnF2Q5"

[bluesky]
account = "plakar.bsky.social"

[linkedin]
account = "company/plakarkorp"
