# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/configuration/#theme-parameters

colorScheme = "plakarium"

[logos]
  icon = "img/logos/plakar-logo-icon.svg"
  dark = "img/logos/plakar-logo-dark.svg"

[github]
  enabled = true
  organization = "PlakarKorp"
  repository = "plakar"

[discord]
  enabled = true
  inviteCode = "uuegtnF2Q5"
  serverID = "1281181647005421589"

[docs]
  latestVersion = "v1.0.6"
  docsRepo = "https://github.com/PlakarKorp/plakar.io"

[socials]
  bluesky = "https://bsky.app/profile/plakar.bsky.social"
  linkedin = "https://www.linkedin.com/company/plakarkorp"
  reddit = "https://www.reddit.com/r/plakar"
  x = "https://x.com/PlakarKorp"

[axeptio]
  enabled = true
  clientId = "670b04f487d8b40de2e7f22c"
  cookiesVersion = "plakar-fr-EU-2"

defaultAppearance = "light"
autoSwitchAppearance = false
enableA11y = false
enableSearch = true
enableCodeCopy = false
enableStructuredBreadcrumbs = false
enableStyledScrollbar = true
replyByEmail = false
disableImageOptimization = false
disableImageOptimizationMD = false
disableTextInHeader = false
hotlinkFeatureImage = false
fingerprintAlgorithm = "sha512"
giteaDefaultServer = "https://git.fsfe.org"
forgejoDefaultServer = "https://v11.next.forgejo.org"

[header]
  layout = "basic"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "profile"
  showRecent = false
  showRecentItems = 5
  showMoreLink = false
  showMoreLinkDest = "/posts/"
  cardView = false
  cardViewScreenWidth = false
  layoutBackgroundBlur = false
  disableHeroImageFilter = false

[article]
  showDate = true
  showViews = false
  showLikes = false
  showDateOnlyInArticle = false
  showDateUpdated = false
  showAuthor = true
  showHero = false
  layoutBackgroundBlur = true
  layoutBackgroundHeaderSpace = true
  showBreadcrumbs = false
  showDraftLabel = true
  showEdit = false
  editAppendPath = true
  seriesOpened = false
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = false
  showTaxonomies = false
  showCategoryOnly = false
  showAuthorsBadges = false
  showWordCount = true
  showZenMode = false

[list]
  showHero = false
  layoutBackgroundBlur = true
  layoutBackgroundHeaderSpace = true
  showBreadcrumbs = false
  showSummary = false
  showViews = false
  showLikes = false
  showTableOfContents = false
  showCards = false
  orderByWeight = false
  groupByYear = true
  cardView = false
  cardViewScreenWidth = false
  constrainItemsWidth = false

[sitemap]
  excludedKinds = ["taxonomy", "term"]

[taxonomy]
  showTermCount = true
  showHero = false
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = false
  cardView = false

[term]
  showHero = false
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = true
  groupByYear = false
  cardView = false
  cardViewScreenWidth = false
