baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Plakar - Effortless backup'
environement = 'development'

[Params]
    logoLight = "img/logo/Plakar_Effortless_Backup_Logo_Light.svg"
    logoDark = "img/logo/Plakar_Effortless_Backup_Logo_Dark.svg"
    logoIcon = "img/logo/Plakar_Effortless_Backup_Logo_Icon.svg"
    footerBanner = "img/plakar-footer-banner.svg"
