baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Hugo Site'

[Params]
    logoLight = "img/Plakar_Effortless_Backup_Logo_Light.svg"
    logoDark = "img/Plakar_Effortless_Backup_Logo_Dark.svg"
    footerBanner = "img/plakar-footer-banner.svg"


