[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.solutions]]
name = 'Solutions'
pageRef = '#'
weight = 20

[[menus.main]]
name = 'Engineering'
pageRef = '#'
weight = 30

[[menus.Connectors]]
name = 'Connectors'
pageRef = '#'
weight = 30


[module]
[module.hugoVersion]
extended = false
min = "0.116.0"