name: Codespell

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: codespell-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  codespell:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Run codespell
        uses: codespell-project/actions-codespell@v2
